### PR TITLE
Add missing formulae

### PR DESCRIPTION
**Pull request by gabrielboliveira**
The release 1.1.3 doesn't have assets on https://github.com/drone/drone-cli/releases, so cannot download that one

### CODE REVIEW

**Review by tboerger — APPROVED** [review]
Not sure if this is still required as the CLI should be part of the official formulas, but code-wise LGTM

**Comment by gabrielboliveira** [comment]
@tboerger Perhaps we should update the docs with the new installation method? I would be happy to open a PR with the new installation 
 
I needed to update my local drone-cli, but installed a while ago with the tap option. Doing this worked:

```sh
brew untap drone/drone
brew uninstall drone
brew update
brew install drone
```

**Comment by hikerspath** [comment]
Would like to see this merged in myself, been a long time, was about to submit the exact same PR myself.  Still in docs to use brew, so the custom tap would still require update as well.
* https://docs.drone.io/cli/install/#install-on-osx

**Comment by bradrydzewski** [comment]
yes, lets merge this and start switching docs over to use the "official" brew installation instead of the custom tap.

**Pull request merged**
